# version: '3.9'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    attach: false
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    attach: false
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    volumes:
      - ./kafka_healthcheck.sh:/kafka_healthcheck.sh
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.0-M02-alpine
    attach: false
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  dispatcher:
    build:
      context: ./containers
      dockerfile: common/Dockerfile
      args:
        CONTAINER_NAME: dispatcher
    container_name: dispatcher
    environment:
      GROUP_ID: dispatch-group
    command: ["sh", "-c", "node --trace-warnings dist/index.js 10"]
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy

  source:
    build:
      context: ./containers
      dockerfile: common/Dockerfile
      args:
        CONTAINER_NAME: source
    container_name: source
    environment:
      GROUP_ID: source-group
    volumes:
      - ./input:/usr/src/app/input
    command: ["sh", "-c", "node --trace-warnings dist/index.js --source"]
    depends_on:
      dispatcher:
        condition: service_started
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
  
  source-2:
    build:
      context: ./containers
      dockerfile: common/Dockerfile
      args:
        CONTAINER_NAME: source-2
    container_name: source-2
    environment:
      GROUP_ID: source-group
    volumes:
      - ./input:/usr/src/app/input
    command: ["sh", "-c", "node --trace-warnings dist/index.js --source"]
    depends_on:
      dispatcher:
        condition: service_started
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
  

  mapper:
    build:
      context: ./containers
      dockerfile: common/Dockerfile
      args:
        CONTAINER_NAME: worker
    environment:
      GROUP_ID: map-group
    command: ["sh", "-c", "node --trace-warnings dist/index.js --map"]
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy

  shuffler:
    build:
      context: ./containers
      dockerfile: common/Dockerfile
      args:
        CONTAINER_NAME: worker
    environment:
      GROUP_ID: shuffle-group
    command: ["sh", "-c", "node --trace-warnings dist/index.js --shuffle"]
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      dispatcher:
        condition: service_started
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy

  reducer:
    build:
      context: ./containers
      dockerfile: common/Dockerfile
      args:
        CONTAINER_NAME: worker
    container_name: reducer
    environment:
      GROUP_ID: reduce-group
    command: ["sh", "-c", "node --trace-warnings dist/index.js --reduce"]
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy

  sink:
    build:
      context: ./containers
      dockerfile: common/Dockerfile
      args:
        CONTAINER_NAME: sink
    container_name: sink
    environment:
      GROUP_ID: sink-group
    volumes:
      - ./output:/usr/src/app/output
    command: ["sh", "-c", "node --trace-warnings dist/index.js --output"]
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
